name = "MOFAM Minimal QAC Test"

plugins = [
	"DLCHorseArmor.esp",
	"DLCHorseArmor - Unofficial Patch.esp",
]

[[mods]]
id = "Cleaned DLC Masters"
section = ["CLEANED MASTERS"]
type = "build-from-files"
files = [
	"%GAME_DIR%/OriginalESPs/DLCHorseArmor.esp",
]
actions = [
	{ action = "qac", plugins = ["DLCHorseArmor.esp"] },
]
