//! `ini_tweak`: write a Wrye Bash INI Tweak fragment into the staged mod.

use super::ActionCx;
use super::ini_set::{IniSetOutcome, apply_ini_set_in_section, render_ini_assignment};
use crate::config::schema::{IniSetFormat, IniTweakAction};
use crate::util::fs::resolve_existing_path_case_insensitive;
use std::path::{Path, PathBuf};

/// Wrye Bash's folder name for tweak fragments, lower-cased like every other
/// directory mudcrab stages: the VFS overlay is case-sensitive here and case
/// is not on Windows, so folding is what makes two mods' `Ini`/`ini` merge.
const TWEAKS_DIR: &str = "ini tweaks";

/// What MO2's wizard puts at the top of a fragment it generates. Kept verbatim
/// rather than replaced with something about mudcrab: this action's whole job
/// is to produce the artefact a BAIN wizard would have, and every other copy of
/// this file in the wild carries that line.
const HEADER: &str = "; Generated by Mod Organizer 2 via Wizard";

/// MO2 is a Windows program writing a Windows INI.
const NEWLINE: &str = "\r\n";

pub(super) fn apply(action: &IniTweakAction, cx: &ActionCx<'_>) -> anyhow::Result<()> {
    let Some(mod_target) = cx.mod_target else {
        anyhow::bail!("{}: ini_tweak is only valid on a per-mod action", cx.owner);
    };

    // A tweak names an INI, not a path: `EditINI` takes the file the game knows
    // and Bash decides where the fragment lives.
    if action.file.contains('/') || action.file.contains('\\') {
        anyhow::bail!(
            "{}: ini_tweak file '{}' is a path; name the INI the tweak is for, \
             and the fragment is written under '{TWEAKS_DIR}/'",
            cx.owner,
            action.file
        );
    }

    let tweak_path = tweak_path(mod_target, &action.file);

    if cx.settings.dry_run {
        tracing::info!(
            owner = cx.owner,
            tweak = %tweak_path.display(),
            key = action.key,
            value = %action.value,
            "install dry-run ini_tweak action"
        );
        return Ok(());
    }

    match resolve_existing_path_case_insensitive(&tweak_path) {
        // A second tweak for the same INI joins the first, which is what a
        // wizard calling `EditINI` twice produces.
        Some(existing) => {
            let outcome = apply_ini_set_in_section(
                &existing,
                None,
                &action.key,
                &action.value.0,
                action.format,
            )?;
            match outcome {
                IniSetOutcome::Replaced => tracing::info!(
                    owner = cx.owner,
                    tweak = %existing.display(),
                    key = action.key,
                    "changed a setting in an existing ini tweak"
                ),
                _ => tracing::info!(
                    owner = cx.owner,
                    tweak = %existing.display(),
                    key = action.key,
                    "added a setting to an existing ini tweak"
                ),
            }
        }
        None => {
            create_tweak(&tweak_path, &action.key, &action.value.0, action.format)?;
            tracing::info!(
                owner = cx.owner,
                tweak = %tweak_path.display(),
                key = action.key,
                value = %action.value,
                "wrote an ini tweak"
            );
        }
    }
    Ok(())
}

fn tweak_path(mod_target: &Path, file: &str) -> PathBuf {
    mod_target.join(TWEAKS_DIR).join(file)
}

fn create_tweak(
    path: &Path,
    key: &str,
    value: &str,
    format: IniSetFormat,
) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // Tight `key=value` for the standard format: Oblivion's parser takes
    // everything after the `=` literally, so a padding space becomes part of
    // the value. `set key to value` is unaffected either way.
    let line = render_ini_assignment(key, value, format, false);
    // No trailing newline -- the file ends on its last setting, as MO2 leaves
    // it, so a later `apply_ini_set_in_section` keeps that shape too.
    std::fs::write(path, format!("{HEADER}{NEWLINE}{line}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_new_tweak_is_the_header_and_one_setting_with_no_trailing_newline() {
        let dir = tempfile::tempdir().unwrap();
        let path = tweak_path(dir.path(), "Oscuro's_Oblivion_Overhaul.ini");

        create_tweak(&path, "OOOOptions.bHK", "0", IniSetFormat::SetTo).unwrap();

        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "; Generated by Mod Organizer 2 via Wizard\r\nset OOOOptions.bHK to 0"
        );
        // The exact size of the Oracle's copy, which is the point of the shape.
        assert_eq!(std::fs::metadata(&path).unwrap().len(), 66);
    }

    /// A wizard calling `EditINI` twice for one INI writes one fragment with
    /// two settings, and the second must not lose the file's CRLF or gain a
    /// trailing newline.
    #[test]
    fn a_second_setting_joins_the_same_fragment() {
        let dir = tempfile::tempdir().unwrap();
        let path = tweak_path(dir.path(), "Mod.ini");

        create_tweak(&path, "A.one", "0", IniSetFormat::SetTo).unwrap();
        apply_ini_set_in_section(&path, None, "A.two", "1", IniSetFormat::SetTo).unwrap();

        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "; Generated by Mod Organizer 2 via Wizard\r\nset A.one to 0\r\nset A.two to 1"
        );
    }

    #[test]
    fn the_folder_is_lower_case_and_the_file_name_is_not() {
        let path = tweak_path(Path::new("/mods/Example"), "Oscuro's_Oblivion_Overhaul.ini");
        assert_eq!(
            path,
            PathBuf::from("/mods/Example/ini tweaks/Oscuro's_Oblivion_Overhaul.ini")
        );
    }
}
